### 矩阵乘法

m×n 矩阵乘以 n×o 矩阵，变成 m×o 矩阵。 

![](https://i.loli.net/2018/11/30/5c00e23814b27.png)


我们可以把它和我们上一节课所讲的矩阵和向量的乘法结合起来, 我们吧矩阵和矩阵的乘法拆解为多个矩阵和向量的乘法,然后再拼接起来,看下图

![](http://imgbed.momodel.cn/5cc1a0b4e3067ce9b6abf762.jpg)


In [2]:
import numpy as np

a = np.mat([[-1,2],[2,3]])
b = np.mat([[3,4],[4,5]])
print ("a: \n",a, "\nb: \n",b)
print("a*b:\n",a*b)


a: 
 [[-1  2]
 [ 2  3]] 
b: 
 [[3 4]
 [4 5]]
a*b:
 [[ 5  6]
 [18 23]]


我们为什么要学习矩阵乘法？

![](http://imgbed.momodel.cn/5cc1a0b5e3067ce9b6abf763.jpg)

假如我们有4个房子的面积数据，有三个 hypotheses，那么我们可以把这些数据写成矩阵的形式，利用矩阵乘法，即可快速进行计算了。